services:
  ##########################################
  # govcms: The GovCMS drupal 10 site used by local PoC
  ##########################################
  govcms:
    build: 
      context: .
      dockerfile: $PWD/Dockerfile.govcms
      secrets:
       - github_token
    ports:
      - 8888:80
    volumes:
      - /var/www/html/sites
      - ./sites/govcms/modules:/app/web/modules/develop
      - ./sites/govcms/themes:/app/web/themes/develop
      - ./sites/govcms/config:/app/web/profiles/govcms/config
    environment:
      GITHUB_TOKEN: /run/secrets/github_token
    secrets:
       - github_token

  ##########################################
  # drupal: The drupal site used by local
  ##########################################
  drupal:
    build: 
      context: .
      dockerfile: $PWD/Dockerfile.drupal
      secrets:
       - github_token
    ports:
      - 8889:80
    volumes:
      - /var/www/html/sites
      - ./sites/drupal10/modules:/var/www/html/modules/develop
      - ./sites/drupal10/themes:/var/www/html/themes/develop
    environment:
      GITHUB_TOKEN: /run/secrets/github_token
    secrets:
       - github_token

  ##########################################
  # drupal9: The drupal site used by local
  ##########################################
  drupal9:
    build:
      context: .
      dockerfile: $PWD/Dockerfile.drupal9
    ports:
      - 8890:80
    volumes:
      - /var/www/html/sites
      - ./sites/drupal9/modules:/var/www/html/modules/develop
      - ./sites/drupal9/themes:/var/www/html/themes/develop

  ##########################################
  # mariadb: The database used by local
  ##########################################
  mariadb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: drupal
      MARIADB_USER: drupal
      MARIADB_PASSWORD: drupal
    volumes:
      - ./database:/var/lib/mysql

secrets:
   github_token:
     file: ./configs/auth.json

networks:
  default:
    external: false