services:
  ##########################################
  # govcms: The GovCMS drupal 10 site used by local PoC
  ##########################################
  govcms:
    build: 
      context: .
      dockerfile: $PWD/Dockerfile.govcms
      secrets:
       - github_token
    ports:
      - 8888:80
    volumes:
      - ./modules/govcms:/var/www/html/modules
      - ./sites/govcms:/var/www/html/sites
      - ./themes/govcms:/var/www/html/themes
    environment:
      GITHUB_TOKEN: /run/secrets/github_token
    secrets:
       - github_token

  ##########################################
  # drupal: The drupal site used by local
  ##########################################
  drupal:
    build: 
      context: .
      dockerfile: $PWD/Dockerfile.drupal
      secrets:
       - github_token
    ports:
      - 8889:80
    volumes:
      - ./modules/drupal10:/var/www/html/modules
      - ./sites/drupal10:/var/www/html/sites
      - ./themes/drupal10:/var/www/html/themes
    environment:
      GITHUB_TOKEN: /run/secrets/github_token
    secrets:
       - github_token

  ##########################################
  # drupal9: The drupal site used by local
  ##########################################
  drupal9:
    build:
      context: .
      dockerfile: $PWD/Dockerfile.drupal9
    ports:
      - 8890:80
    volumes:
      - ./modules/drupal9:/var/www/html/modules
      - ./sites/drupal9:/var/www/html/sites
      - ./themes/drupal9:/var/www/html/themes

  ##########################################
  # mariadb: The database used by local
  ##########################################
  mariadb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: drupal
      MARIADB_USER: drupal
      MARIADB_PASSWORD: drupal
    volumes:
      - ./database:/var/lib/mysql

secrets:
   github_token:
     file: ./configs/auth.json

networks:
  default:
    external: false